"""Full 1:1 mirror of the 20 target accounts + their contacts into Supabase.

Every column of internal.marketing.brands (567) and .brand_contacts (734) is
mirrored. Nested ARRAY/OBJECT/VARIANT columns become jsonb. The schema is
generated dynamically from Snowflake's information_schema, so it tracks the
source tables.

Usage (from backend/, with the venv):
    PYTHONPATH=. python scripts/ingest_target_full.py ddl   # -> writes .sql files
    PYTHONPATH=. python scripts/ingest_target_full.py load  # -> upserts data
"""

import json
import math
import sys
from datetime import date, datetime
from decimal import Decimal

from app.snowflake_client import query_snowflake
from app.supabase_client import get_client

DOMAINS = [
    "urbanstems.com", "benchmade.com", "cozyearth.com", "staud.clothing",
    "suitshop.com", "shopmelissa.com", "denimtears.com", "marinelayer.com",
    "thuma.co", "shapermint.com", "skullshaver.com", "jaanuu.com",
    "davidprotein.com", "lifestraw.com", "thenormalbrand.com", "clivecoffee.com",
    "andcollar.com", "boysmells.com", "topodesigns.com", "modloft.com",
]
SEED = {
    "urbanstems.com": ("UrbanStems", 176, "mvp"),
    "benchmade.com": ("Benchmade", 156, "mvp"),
    "cozyearth.com": ("Cozy Earth", 92, "mvp+price+li"),
    "staud.clothing": ("STAUD", 87, "mvp"),
    "suitshop.com": ("SuitShop", 82, "mvp"),
    "shopmelissa.com": ("Melissa", 66, "mvp"),
    "denimtears.com": ("Denim Tears", 60, "mvp"),
    "marinelayer.com": ("Marine Layer", 60, "mvp"),
    "thuma.co": ("Thuma", 54, "mvp+li"),
    "shapermint.com": ("Shapermint", 46, "mvp+li"),
    "skullshaver.com": ("Skull Shaver", 46, "mvp"),
    "jaanuu.com": ("Jaanuu", 39, "mvp"),
    "davidprotein.com": ("David Protein", 30, "mvp"),
    "lifestraw.com": ("LifeStraw", 29, "mvp+rev"),
    "thenormalbrand.com": ("Normal Brand", 29, "mvp"),
    "clivecoffee.com": ("Clive", 26, "mvp"),
    "andcollar.com": ("&Collar", 25, "mvp+li"),
    "boysmells.com": ("Boy Smells", 22, "mvp+rev"),
    "topodesigns.com": ("Topo Designs", 22, "mvp"),
    "modloft.com": ("Modloft", 16, "mvp"),
}

ACCOUNTS_TABLE = "hackathon_target_accounts"
CONTACTS_TABLE = "hackathon_target_contacts"

# Snowflake -> Postgres type map. Nested types collapse to jsonb.
PG_TYPE = {
    "TEXT": "text", "NUMBER": "numeric", "FLOAT": "double precision",
    "BOOLEAN": "boolean", "DATE": "date", "TIMESTAMP_NTZ": "timestamp",
    "TIMESTAMP_TZ": "timestamptz", "TIMESTAMP_LTZ": "timestamptz",
    "ARRAY": "jsonb", "OBJECT": "jsonb", "VARIANT": "jsonb",
}
JSONB_SF = {"ARRAY", "OBJECT", "VARIANT"}


def sf_columns(table: str):
    return query_snowflake(
        """SELECT column_name, data_type FROM internal.information_schema.columns
           WHERE table_schema='MARKETING' AND table_name=? ORDER BY ordinal_position""",
        [table],
    )


def _table_sql(pg_table: str, sf_table: str, pk: str, extra: list[str], index_col=None):
    lines = [
        f'  "{c["COLUMN_NAME"].lower()}" {PG_TYPE.get(c["DATA_TYPE"], "text")}'
        for c in sf_columns(sf_table)
    ]
    lines += extra + ['  "_ingested_at" timestamptz not null default now()']
    parts = [
        f"create table public.{pg_table} (",
        ",\n".join(lines) + f',\n  primary key ("{pk}")',
        ");",
        f"alter table public.{pg_table} enable row level security;",
    ]
    if index_col:
        parts.append(f'create index on public.{pg_table} ("{index_col}");')
    return "\n".join(parts)


SCHEMA_PATH = "scripts/target_full_schema.sql"


def write_ddl():
    accounts = _table_sql(
        ACCOUNTS_TABLE, "BRANDS", "domain",
        ['  "seed_brand" text', '  "seed_gmv_musd" numeric', '  "seed_sig" text'],
    )
    contacts = _table_sql(
        CONTACTS_TABLE, "BRAND_CONTACTS", "id", [], index_col="parent_domain"
    )
    sql = "\n".join(
        [
            "-- Full 1:1 mirror of internal.marketing.brands (567 cols) and",
            "-- internal.marketing.brand_contacts (734 cols) for the 20 target accounts.",
            "-- Nested ARRAY/OBJECT/VARIANT -> jsonb. Generated by ingest_target_full.py ddl.",
            "-- Apply in the Supabase SQL editor (project vmpzkytxdruwbdftxtnm), then run:",
            "--   PYTHONPATH=. python scripts/ingest_target_full.py load",
            "",
            "drop table if exists public.hackathon_target_contacts cascade;",
            "drop table if exists public.hackathon_target_accounts cascade;",
            "",
            accounts,
            "",
            contacts,
            "",
        ]
    )
    with open(SCHEMA_PATH, "w") as f:
        f.write(sql)
    print(f"wrote {SCHEMA_PATH}")


def _coerce(v, sf_type):
    if v is None:
        return None
    if sf_type in JSONB_SF:
        if isinstance(v, str):
            try:
                return json.loads(v)
            except json.JSONDecodeError:
                return v
        return v
    if isinstance(v, Decimal):
        return float(v)
    if isinstance(v, (datetime, date)):
        return v.isoformat()
    if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):
        return None
    return v


def _rows(sf_table: str, where: str):
    types = {c["COLUMN_NAME"].upper(): c["DATA_TYPE"] for c in sf_columns(sf_table)}
    ph = ",".join(["?"] * len(DOMAINS))
    raw = query_snowflake(
        f"SELECT * FROM internal.marketing.{sf_table} WHERE {where.format(ph=ph)}",
        [d.lower() for d in DOMAINS],
    )
    for r in raw:
        yield {k.lower(): _coerce(v, types.get(k, "TEXT")) for k, v in r.items()}


def _upsert(table: str, records: list[dict], pk: str, batch=25):
    t = get_client().table(table)
    for i in range(0, len(records), batch):
        t.upsert(records[i : i + batch], on_conflict=pk).execute()


def load():
    accounts = list(_rows("BRANDS", "LOWER(domain) IN ({ph})"))
    for rec in accounts:
        brand, gmv, sig = SEED[rec["domain"].lower()]
        rec["seed_brand"], rec["seed_gmv_musd"], rec["seed_sig"] = brand, gmv, sig
    _upsert(ACCOUNTS_TABLE, accounts, "domain")
    print(f"upserted {len(accounts)} accounts ({len(accounts[0])} cols each)")

    contacts = list(_rows("BRAND_CONTACTS", "LOWER(parent_domain) IN ({ph}) AND id IS NOT NULL"))
    seen, deduped = set(), []
    for rec in contacts:
        if rec["id"] in seen:
            continue
        seen.add(rec["id"])
        deduped.append(rec)
    _upsert(CONTACTS_TABLE, deduped, "id")
    print(f"upserted {len(deduped)} contacts ({len(deduped[0])} cols each)")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "load"
    (write_ddl if cmd == "ddl" else load)()
